version: '3'

services:

  jenkins:
    container_name: jenkins
    image: jenkins/jenkins
    restart: unless-stopped
    hostname: jenkins
    ports:
      - "8085:8080"
    volumes:
      - jn-vol:/var/jenkins_home
    networks:
      - jn-net

  gitlab:
    container_name: gitlab
    image: 'gitlab/gitlab-ce:latest'
    restart: unless-stopped
    hostname: gitlab
    ports:
      - "8090:80"
    volumes:
      - "/var/gitlab/config:/etc/gitlab"
      - "/var/gitlab/logs:/var/log/gitlab"
      - "/var/gitlab/data:/var/opt/gitlab"
    networks:
      - jn-net

volumes:
  jn-vol:

networks:
  jn-net:
